language: python
python:
- 3.6
install:
- pip install codecov
- pip install -U tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davidemoro
  password:
    secure: S9Z9S/dmsqOWRR0iTQgO8H31ncpVHTl+bLPeH0O6tG+T6kETrSfldR8hcRSQ264T6wxWVrMFoKYsUCGWLIdFW8ges2FbYMk7Ncv8kH0QGHyHgxtjQ6370qzjjj1oGzdQSJff2plAWkk1uGXu2fdEfbcIBd9YR86DTw6HpIijCgvWqbVz6ZHCJHXvVHwKbwee5r9YQHwn6zLLsQXib0U+ah9HI4IsfZe0wJt0rLbdUoTv72nrTG+l5mhBLetkzwbH/I+VABeaaVwjMM/LuQXuvg4np7DqmbZZ091mrFMwCoyjdrnoTeFSybtcLCzqD42msnskf+U2CmwslxbYkuJnE7jjp2aaryA+Zq6XLD92qE0DPqf3BUVLr0BkCVFvX11dJB2wNJV1QhZjOrqkI/F/YvetyJgJwZdGvmH/9OL+7V4rrwFcycW+Y/gg62oaMfon5HZKCLV/7iey1l02bzMYfoN3E8JaT/xz7PTZ5dnjjqAxcHmxj1aH3OYqymMCd8Sh0jHtKs0AxH4vMcUk0PXttn9N/0+JYdaCfRzMz/A7mV1mthBY1CohjAyT8/IMyjxhQomPALuucZR5QVGRWBmlZT3Jnnm+YkrVI699LBeDxM82zTPLVqXisGtU+9YOoMbAF8XlxhYTDH7nTK61fwMXssG4f0iIuVV8deKrxiW0p0g=
  on:
    tags: true
    repo: davidemoro/play_dynamodb
    python: 3.6
